name: yolo

on:
  push:

jobs:
  yolo:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: necko-actions/setup-smithy@v1
        with:
          version: 1.52.1
      - run: smithy --version
